allowBuilds:
  scrollreveal: false
# minimumReleaseAge: 1440
# trustPolicy: no-downgrade
minimumReleaseAgeExclude:
  - daisyui@5.6.3 || 5.6.6 || 5.6.7 || 5.6.10 || 5.6.14 || 5.6.16 || 5.6.17 || 5.6.18 || 5.7.0 || 5.7.8 || 5.7.9 || 5.7.14 || 5.7.15 || 5.7.17 || 5.7.19 || 5.7.20 || 5.7.22 || 5.7.23 || 5.7.25
  - eslint@10.6.0 || 10.7.0 || 10.8.1 || 10.9.1
  - '@tailwindcss/node@4.3.2'
  - '@tailwindcss/oxide-android-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-arm64@4.3.2'
  - '@tailwindcss/oxide-darwin-x64@4.3.2'
  - '@tailwindcss/oxide-freebsd-x64@4.3.2'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.2'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.2'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.2'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.2'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.2'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.2'
  - '@tailwindcss/oxide@4.3.2'
  - '@tailwindcss/vite@4.3.2'
  - '@typescript-eslint/eslint-plugin@8.62.1 || 8.65.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/parser@8.62.1 || 8.65.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/project-service@8.62.1 || 8.65.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/scope-manager@8.62.1 || 8.65.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/tsconfig-utils@8.62.1 || 8.65.0 || 8.66.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/type-utils@8.62.1 || 8.65.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/types@8.62.1 || 8.65.0 || 8.66.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/typescript-estree@8.62.1 || 8.65.0 || 8.66.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/utils@8.62.1 || 8.65.0 || 8.66.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - '@typescript-eslint/visitor-keys@8.62.1 || 8.65.0 || 8.67.0 || 8.68.0 || 8.69.0'
  - tailwindcss@4.3.2
  - typescript-eslint@8.62.1 || 8.65.0 || 8.67.0 || 8.68.0 || 8.69.0
  - '@types/node@26.1.0 || 26.1.1 || 26.2.0 || 26.3.0'
  - vite@8.1.3 || 8.2.0 || 8.2.1
  - '@typescript/typescript-aix-ppc64@7.0.2'
  - '@typescript/typescript-darwin-arm64@7.0.2'
  - '@typescript/typescript-darwin-x64@7.0.2'
  - '@typescript/typescript-freebsd-arm64@7.0.2'
  - '@typescript/typescript-freebsd-x64@7.0.2'
  - '@typescript/typescript-linux-arm64@7.0.2'
  - '@typescript/typescript-linux-arm@7.0.2'
  - '@typescript/typescript-linux-loong64@7.0.2'
  - '@typescript/typescript-linux-mips64el@7.0.2'
  - '@typescript/typescript-linux-ppc64@7.0.2'
  - '@typescript/typescript-linux-riscv64@7.0.2'
  - '@typescript/typescript-linux-s390x@7.0.2'
  - '@typescript/typescript-linux-x64@7.0.2'
  - '@typescript/typescript-netbsd-arm64@7.0.2'
  - '@typescript/typescript-netbsd-x64@7.0.2'
  - '@typescript/typescript-openbsd-arm64@7.0.2'
  - '@typescript/typescript-openbsd-x64@7.0.2'
  - '@typescript/typescript-sunos-x64@7.0.2'
  - '@typescript/typescript-win32-arm64@7.0.2'
  - '@typescript/typescript-win32-x64@7.0.2'
  - typescript@7.0.2
  - '@vitejs/plugin-react@6.0.4 || 6.0.5 || 6.1.0'
  - react@19.2.8 || 19.3.0
  - react-dom@19.2.8 || 19.3.0
  - axios@1.19.0
  - '@types/react-dom@19.2.4 || 19.3.0'
  - '@types/react@19.2.18 || 19.3.0'
  - '@hookform/resolvers@5.6.0 || 5.7.1'
  - react-hook-form@7.84.0 || 7.85.0
  - globals@17.9.0 || 17.12.0
  - eslint-plugin-react-refresh@0.5.4
  - scheduler@0.28.0
  - zod@4.6.1
onlyBuiltDependencies:
  - esbuild
  - scrollreveal
